title: This is our Flatgame
hero_image: images/banner.png
description: default-project-template description
version: 1
listed: false
copyedit: false
last_tested: "2025-01-01"
steps:
  - title: What you will make
  - title: What is a Flatgame?
  - title: Make the artwork
  - title: Get photos to your device
  - title: Adding background 
  - title: Scrolling 
  - title: Add a main sprite
  - title: Moving the main sprite
  - title: Adding artwork!
  - title: Challenge
